version: '2'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    hostname: localhost
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - "0.0.0.0:27017:27017"
    environment:
      MONGO_INITDB_ROOT_DATABASE: main
      MONGO_INITDB_ROOT_USERNAME: debeziumUser
      MONGO_INITDB_ROOT_PASSWORD: debeziumUser

  node_app:
    container_name: node_app
    image: teqsk1514/cdc-node-app:v0
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://debeziumUser:debeziumUser@mongo:27017
      - MESSAGE_FLUSH_TIME_MS=2000
      - PRINT_MESSAGE_BOOL=true
      - DB_NAME=debezium_db
      - COLLECTION_NAME=users
      - MESSAGE_COUNT=10
    ports:
      - "5000:5000"

  mongo-ui:
    image: huggingface/mongoku
    container_name: mongo-ui
    restart: always
    environment:
      - MONGOKU_DEFAULT_HOST=mongodb://debeziumUser:debeziumUser@mongo:27017
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - '3100:3100'